#include "gf_mux.h"

#include <common.h>
#include <i2c.h>
#include <asm/io.h>
#include <asm/gpio.h>
#include <asm/arch/mx7-pins.h>
#include <asm/arch/crm_regs.h>
#include <asm/arch/sys_proto.h>
#include <asm/imx-common/boot_mode.h>
#include <asm/imx-common/iomux-v3.h>
#include <asm/imx-common/mxc_i2c.h>
#include <asm/arch/imx-regs.h>

#define UART_PAD_CTRL  (PAD_CTL_DSE_3P3V_49OHM | \
	PAD_CTL_PUS_PU100KOHM | PAD_CTL_HYS)

#define I2C_PAD_CTRL    (PAD_CTL_DSE_3P3V_32OHM | PAD_CTL_SRE_SLOW | \
	PAD_CTL_HYS | PAD_CTL_PUE | PAD_CTL_PUS_PU100KOHM)

#define LCD_PAD_CTRL    (PAD_CTL_HYS | PAD_CTL_PUS_PU100KOHM | \
	PAD_CTL_DSE_3P3V_49OHM)

#define DIO_PDOWN_PAD_CTRL (PAD_CTL_HYS | PAD_CTL_PUS_PD100KOHM | \
	PAD_CTL_DSE_3P3V_49OHM)

#define DIO_PUP_PAD_CTRL (PAD_CTL_HYS | PAD_CTL_PUS_PU47KOHM | \
	PAD_CTL_DSE_3P3V_49OHM)

#define USDHC_PAD_CTRL (PAD_CTL_DSE_3P3V_32OHM | PAD_CTL_SRE_SLOW | \
	PAD_CTL_HYS | PAD_CTL_PUE | PAD_CTL_PUS_PU47KOHM)

#define AUDIO_PAD_CTRL (PAD_CTL_PUS_PD100KOHM | 	\
	PAD_CTL_DSE_3P3V_49OHM | PAD_CTL_SRE_SLOW | PAD_CTL_HYS)

#define ENET_PAD_CTRL  (PAD_CTL_PUS_PU100KOHM | PAD_CTL_DSE_3P3V_49OHM)

#define ENET_RX_PAD_CTRL  (PAD_CTL_PUS_PU100KOHM | PAD_CTL_DSE_3P3V_49OHM)

#define ENET_PAD_CTRL_MII  (PAD_CTL_DSE_3P3V_32OHM)

#define SPI_PAD_CTRL (PAD_CTL_HYS | PAD_CTL_DSE_3P3V_49OHM)

/* UART1 */
static iomux_v3_cfg_t const uart1_pads[] = {
	MX7D_PAD_UART1_TX_DATA__UART1_DCE_TX | MUX_PAD_CTRL(UART_PAD_CTRL),
	MX7D_PAD_UART1_RX_DATA__UART1_DCE_RX | MUX_PAD_CTRL(UART_PAD_CTRL),
};

/* UART2 */
static iomux_v3_cfg_t const uart2_pads[] = {
	MX7D_PAD_UART2_TX_DATA__UART2_DCE_TX | MUX_PAD_CTRL(UART_PAD_CTRL),
	MX7D_PAD_UART2_RX_DATA__UART2_DCE_RX | MUX_PAD_CTRL(UART_PAD_CTRL),
	MX7D_PAD_SAI2_RX_DATA__UART2_DCE_CTS | MUX_PAD_CTRL(UART_PAD_CTRL),
	MX7D_PAD_SAI2_TX_DATA__UART2_DCE_RTS | MUX_PAD_CTRL(UART_PAD_CTRL),
};

/* UART5 */
static iomux_v3_cfg_t const uart5_pads[] = {
	MX7D_PAD_I2C4_SCL__UART5_DCE_RX | MUX_PAD_CTRL(UART_PAD_CTRL),
	MX7D_PAD_I2C4_SDA__UART5_DCE_TX | MUX_PAD_CTRL(UART_PAD_CTRL),
	MX7D_PAD_GPIO1_IO04__UART5_CTS_B | MUX_PAD_CTRL(UART_PAD_CTRL),
	MX7D_PAD_GPIO1_IO05__UART5_RTS_B | MUX_PAD_CTRL(UART_PAD_CTRL),
};

/* UART7 */
static iomux_v3_cfg_t const uart7_pads[] = {
	MX7D_PAD_EPDC_DATA13__UART7_DCE_TX | MUX_PAD_CTRL(UART_PAD_CTRL),
	MX7D_PAD_EPDC_DATA12__UART7_DCE_RX | MUX_PAD_CTRL(UART_PAD_CTRL),
};

/* I2C1 for PMIC and EEPROM */
static struct i2c_pads_info i2c_pad_info1 = {
	.scl = {
		.i2c_mode =  MX7D_PAD_I2C1_SCL__I2C1_SCL 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gpio_mode = MX7D_PAD_I2C1_SCL__GPIO4_IO8 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gp = IMX_GPIO_NR(4, 8),
	},
	.sda = {
		.i2c_mode = MX7D_PAD_I2C1_SDA__I2C1_SDA 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gpio_mode = MX7D_PAD_I2C1_SDA__GPIO4_IO9 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gp = IMX_GPIO_NR(4, 9),
	},
};

/* I2C3 */
static struct i2c_pads_info i2c_pad_info3 = {
	.scl = {
		.i2c_mode =  MX7D_PAD_I2C3_SCL__I2C3_SCL 		| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gpio_mode = MX7D_PAD_I2C3_SCL__GPIO4_IO12 		| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gp = IMX_GPIO_NR(4, 12),
	},
	.sda = {
		.i2c_mode = MX7D_PAD_I2C3_SDA__I2C3_SDA 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gpio_mode = MX7D_PAD_I2C3_SDA__GPIO4_IO13 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gp = IMX_GPIO_NR(4, 13),
	},
};

/* LCD RGB interface */
static iomux_v3_cfg_t const lcd_pads[] = {
	MX7D_PAD_LCD_CLK__LCD_CLK 			| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_ENABLE__LCD_ENABLE 	| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_HSYNC__LCD_HSYNC 		| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_VSYNC__LCD_VSYNC 		| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA00__LCD_DATA0 		| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA01__LCD_DATA1 		| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA02__LCD_DATA2 		| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA03__LCD_DATA3 		| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA04__LCD_DATA4 		| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA05__LCD_DATA5 		| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA06__LCD_DATA6 		| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA07__LCD_DATA7 		| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA08__LCD_DATA8 		| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA09__LCD_DATA9 		| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA10__LCD_DATA10 	| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA11__LCD_DATA11		| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA12__LCD_DATA12		| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA13__LCD_DATA13 	| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA14__LCD_DATA14 	| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA15__LCD_DATA15 	| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA16__LCD_DATA16 	| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA17__LCD_DATA17 	| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA18__LCD_DATA18 	| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA19__LCD_DATA19 	| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA20__LCD_DATA20 	| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA21__LCD_DATA21 	| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA22__LCD_DATA22 	| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_DATA23__LCD_DATA23		| MUX_PAD_CTRL(LCD_PAD_CTRL),
	MX7D_PAD_LCD_RESET__GPIO3_IO4		| MUX_PAD_CTRL(DIO_PDOWN_PAD_CTRL), // DISPLAY-EN-3V3 - GPIO3-IO04
	MX7D_PAD_GPIO1_IO02__GPIO1_IO2 		| MUX_PAD_CTRL(DIO_PDOWN_PAD_CTRL), // DISPLAY_BL_CONTROL
	MX7D_PAD_EPDC_DATA04__GPIO2_IO4		| MUX_PAD_CTRL(DIO_PDOWN_PAD_CTRL), // DISPLAY_VDD_CONTROL
};

static iomux_v3_cfg_t const sd1_pads[] = {
	MX7D_PAD_SD1_CLK__SD1_CLK 		| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD1_CMD__SD1_CMD 		| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD1_DATA0__SD1_DATA0 	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD1_DATA1__SD1_DATA1 	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD1_DATA2__SD1_DATA2 	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD1_DATA3__SD1_DATA3 	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD1_RESET_B__GPIO5_IO2	| MUX_PAD_CTRL(DIO_PDOWN_PAD_CTRL) , // LED_WIFI_LINK
};

static iomux_v3_cfg_t const sd2_pads[] = {
	MX7D_PAD_SD2_CLK__SD2_CLK 		| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD2_CMD__SD2_CMD 		| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD2_DATA0__SD2_DATA0 	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD2_DATA1__SD2_DATA1 	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD2_DATA2__SD2_DATA2 	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD2_DATA3__SD2_DATA3 	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD2_CD_B__GPIO5_IO9	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
};

static iomux_v3_cfg_t const sd3_pads[] = {
	MX7D_PAD_SD3_CLK__SD3_CLK 		| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD3_CMD__SD3_CMD 		| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD3_DATA0__SD3_DATA0 	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD3_DATA1__SD3_DATA1 	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD3_DATA2__SD3_DATA2 	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD3_DATA3__SD3_DATA3 	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD3_DATA4__SD3_DATA4 	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD3_DATA5__SD3_DATA5 	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD3_DATA6__SD3_DATA6 	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD3_DATA7__SD3_DATA7 	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD3_STROBE__SD3_STROBE	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD3_RESET_B__SD3_RESET_B	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
};

static iomux_v3_cfg_t const eeprom_pads[] = {
	MX7D_PAD_SD1_WP__GPIO5_IO1	| MUX_PAD_CTRL(DIO_PDOWN_PAD_CTRL),
};

static iomux_v3_cfg_t const audio_pads[] = {
	MX7D_PAD_SAI1_RX_DATA__SAI1_RX_DATA0 | MUX_PAD_CTRL(AUDIO_PAD_CTRL),
	MX7D_PAD_SAI1_TX_DATA__SAI1_TX_DATA0 | MUX_PAD_CTRL(AUDIO_PAD_CTRL),
	MX7D_PAD_SAI1_TX_SYNC__SAI1_TX_SYNC | MUX_PAD_CTRL(AUDIO_PAD_CTRL),
	MX7D_PAD_SAI1_TX_BCLK__SAI1_TX_BCLK | MUX_PAD_CTRL(AUDIO_PAD_CTRL),
	MX7D_PAD_SAI1_MCLK__SAI1_MCLK | MUX_PAD_CTRL(AUDIO_PAD_CTRL),
};

static iomux_v3_cfg_t const enet_pads[] = {
	MX7D_PAD_EPDC_BDR0__CCM_ENET_REF_CLK2 | MUX_PAD_CTRL(ENET_PAD_CTRL) | MUX_MODE_SION,
	MX7D_PAD_EPDC_SDCE0__ENET2_RGMII_RX_CTL | MUX_PAD_CTRL(ENET_RX_PAD_CTRL),
	MX7D_PAD_EPDC_SDCE1__ENET2_RX_ER | MUX_PAD_CTRL(ENET_RX_PAD_CTRL),
	MX7D_PAD_EPDC_SDCE2__ENET2_RGMII_TD0 | MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX7D_PAD_EPDC_SDCE3__ENET2_RGMII_TD1 | MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX7D_PAD_EPDC_SDCLK__ENET2_RGMII_RD0 | MUX_PAD_CTRL(ENET_RX_PAD_CTRL),
	MX7D_PAD_EPDC_SDLE__ENET2_RGMII_RD1 | MUX_PAD_CTRL(ENET_RX_PAD_CTRL),
	MX7D_PAD_EPDC_GDRL__ENET2_RGMII_TX_CTL | MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX7D_PAD_GPIO1_IO14__ENET2_MDIO | MUX_PAD_CTRL(ENET_PAD_CTRL_MII),
	MX7D_PAD_GPIO1_IO15__ENET2_MDC | MUX_PAD_CTRL(ENET_PAD_CTRL_MII),
	MX7D_PAD_ENET1_CRS__GPIO7_IO14 | MUX_PAD_CTRL(DIO_PDOWN_PAD_CTRL),	// ENET_nRST
	MX7D_PAD_ENET1_COL__GPIO7_IO15 | MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),  // ENET_nINT

};

static iomux_v3_cfg_t const gpio_pads[] = {
	MX7D_PAD_GPIO1_IO08__GPIO1_IO8 | MUX_PAD_CTRL(DIO_PUP_PAD_CTRL), // TEMP_ALERT
	MX7D_PAD_GPIO1_IO00__GPIO1_IO0 | MUX_PAD_CTRL(DIO_PUP_PAD_CTRL), // RTC_nINT
};

static iomux_v3_cfg_t const touch_pads[] = {
	MX7D_PAD_SD2_WP__GPIO5_IO10 | MUX_PAD_CTRL(DIO_PUP_PAD_CTRL) | MUX_MODE_SION, // TS-nIRQ
	MX7D_PAD_SD2_RESET_B__GPIO5_IO11 | MUX_PAD_CTRL(DIO_PUP_PAD_CTRL), // TS-nRST
};

static iomux_v3_cfg_t const ecspi3_pads[] = {
	MX7D_PAD_I2C2_SCL__ECSPI3_SCLK | MUX_PAD_CTRL(SPI_PAD_CTRL),
	MX7D_PAD_I2C2_SDA__GPIO4_IO11 | MUX_PAD_CTRL(SPI_PAD_CTRL) | MUX_MODE_SION, // SS0
	MX7D_PAD_SAI2_TX_BCLK__ECSPI3_MOSI | MUX_PAD_CTRL(SPI_PAD_CTRL),
	MX7D_PAD_SAI2_TX_SYNC__ECSPI3_MISO | MUX_PAD_CTRL(SPI_PAD_CTRL),
};

static iomux_v3_cfg_t const usb_hub_pads[] = {
	MX7D_PAD_SAI1_RX_BCLK__GPIO6_IO17 | MUX_PAD_CTRL(DIO_PUP_PAD_CTRL), // VUSB-H2-EN
	MX7D_PAD_SAI1_RX_SYNC__GPIO6_IO16 | MUX_PAD_CTRL(DIO_PUP_PAD_CTRL), // VUSB-H2-nOC
	MX7D_PAD_UART3_CTS_B__GPIO4_IO7 | MUX_PAD_CTRL(DIO_PUP_PAD_CTRL), // VUSB-H1-EN
	MX7D_PAD_UART3_RTS_B__GPIO4_IO6 | MUX_PAD_CTRL(DIO_PUP_PAD_CTRL), // VUSB-H1-nOC
	MX7D_PAD_EPDC_DATA08__GPIO2_IO8 | MUX_PAD_CTRL(DIO_PUP_PAD_CTRL), // VUSB-H4-EN
	MX7D_PAD_EPDC_DATA10__GPIO2_IO10 | MUX_PAD_CTRL(DIO_PUP_PAD_CTRL), // VUSB-H4-nOC
	MX7D_PAD_EPDC_DATA09__GPIO2_IO9 | MUX_PAD_CTRL(DIO_PUP_PAD_CTRL), // VUSB-H3-EN
	MX7D_PAD_EPDC_DATA11__GPIO2_IO11 | MUX_PAD_CTRL(DIO_PUP_PAD_CTRL), // VUSB-H3-nOC
	MX7D_PAD_ENET1_TX_CLK__GPIO7_IO12 | MUX_PAD_CTRL(DIO_PDOWN_PAD_CTRL), // USB-HUB-nRESET
	MX7D_PAD_ENET1_RX_CLK__GPIO7_IO13 | MUX_PAD_CTRL(DIO_PDOWN_PAD_CTRL), // USB-HUB-CONNECT
	MX7D_PAD_SD1_CD_B__GPIO5_IO0 | MUX_PAD_CTRL(DIO_PUP_PAD_CTRL), // USB-HUB-nINT
};

static void my_usb_hub_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(usb_hub_pads, ARRAY_SIZE(usb_hub_pads));
	gpio_direction_output(IMX_GPIO_NR(4,7),1);
	gpio_direction_output(IMX_GPIO_NR(6,17),1);
	gpio_direction_output(IMX_GPIO_NR(2,8),1);
	gpio_direction_output(IMX_GPIO_NR(2,9),1);
}

static void my_ecspi_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(ecspi3_pads, ARRAY_SIZE(ecspi3_pads));
}

static void my_touch_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(touch_pads, ARRAY_SIZE(touch_pads));
}

static void my_gpio_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(gpio_pads, ARRAY_SIZE(gpio_pads));
}

static void my_enet_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(enet_pads, ARRAY_SIZE(enet_pads));
}

static void my_audio_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(audio_pads, ARRAY_SIZE(audio_pads));
}

static void my_uart_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(uart1_pads, ARRAY_SIZE(uart1_pads));
	imx_iomux_v3_setup_multiple_pads(uart2_pads, ARRAY_SIZE(uart2_pads));
	imx_iomux_v3_setup_multiple_pads(uart5_pads, ARRAY_SIZE(uart5_pads));
	imx_iomux_v3_setup_multiple_pads(uart7_pads, ARRAY_SIZE(uart7_pads));
}

static void my_i2c_init_mux(void)
{
	setup_i2c(0, CONFIG_SYS_I2C_SPEED, 0x7f, &i2c_pad_info1);
	setup_i2c(2, CONFIG_SYS_I2C_SPEED, 0x7f, &i2c_pad_info3);
}

static void my_lcd_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(lcd_pads, ARRAY_SIZE(lcd_pads));
}

static void my_sdio_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(sd1_pads, ARRAY_SIZE(sd1_pads));
	imx_iomux_v3_setup_multiple_pads(sd2_pads, ARRAY_SIZE(sd2_pads));
	imx_iomux_v3_setup_multiple_pads(sd3_pads, ARRAY_SIZE(sd3_pads));
}

static void my_eeprom_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(eeprom_pads, ARRAY_SIZE(eeprom_pads));
}

void egf_board_mux_init(int mode)
{
	switch(mode){
	case PROGRAMMER_MUX_MODE:
		my_uart_init_mux();
		my_i2c_init_mux();
		my_ecspi_init_mux();
//		my_spinor_init_mux();
//		my_nand_init_mux();
		my_lcd_init_mux();
		my_sdio_init_mux();
		my_enet_init_mux();
		my_eeprom_init_mux();
		break;
	case APPLICATION_MUX_MODE:
		my_uart_init_mux();
		my_i2c_init_mux();
		my_ecspi_init_mux();
//		my_can_init_mux();
		my_gpio_init_mux();
//		my_spinor_init_mux();
		my_lcd_init_mux();
		my_enet_init_mux();
//		my_usb_init_mux();
		my_sdio_init_mux();
//		my_adc_init_mux();
//		my_buzzer_init_mux();
		my_eeprom_init_mux();
		my_touch_init_mux();
		my_audio_init_mux();
		my_usb_hub_init_mux();
		break;
	default:
		//printf("MUX MODE NOT DEFINED!!!!!!!!!!!!\n");
		break;
	}
}





