#include "gf_mux.h"

#include <common.h>
#include <i2c.h>
#include <asm/io.h>
#include <asm/gpio.h>
#include <asm/arch/mx7-pins.h>
#include <asm/arch/crm_regs.h>
#include <asm/arch/sys_proto.h>
#include <asm/imx-common/boot_mode.h>
#include <asm/imx-common/iomux-v3.h>
#include <asm/imx-common/mxc_i2c.h>
#include <asm/arch/imx-regs.h>

#define UART_PAD_CTRL  (PAD_CTL_DSE_3P3V_49OHM | \
	PAD_CTL_PUS_PU100KOHM | PAD_CTL_HYS)

#define I2C_PAD_CTRL    (PAD_CTL_DSE_3P3V_32OHM | PAD_CTL_SRE_SLOW | \
	PAD_CTL_HYS | PAD_CTL_PUE | PAD_CTL_PUS_PU100KOHM)

#define LCD_PAD_CTRL    (PAD_CTL_HYS | PAD_CTL_PUS_PU100KOHM | \
	PAD_CTL_DSE_3P3V_49OHM)

#define DIO_PDOWN_PAD_CTRL (PAD_CTL_HYS | PAD_CTL_PUS_PD100KOHM | \
	PAD_CTL_DSE_3P3V_49OHM)

#define DIO_PUP_PAD_CTRL (PAD_CTL_HYS | PAD_CTL_PUS_PU47KOHM | \
	PAD_CTL_DSE_3P3V_49OHM)

#define USDHC_PAD_CTRL (PAD_CTL_DSE_3P3V_32OHM | PAD_CTL_SRE_SLOW | \
	PAD_CTL_HYS | PAD_CTL_PUE | PAD_CTL_PUS_PU47KOHM)

#define AUDIO_PAD_CTRL (PAD_CTL_PUS_PD100KOHM | 	\
	PAD_CTL_DSE_3P3V_49OHM | PAD_CTL_SRE_SLOW | PAD_CTL_HYS)

#define ENET_PAD_CTRL  (PAD_CTL_PUS_PU100KOHM | PAD_CTL_DSE_3P3V_49OHM)

#define ENET_RX_PAD_CTRL  (PAD_CTL_PUS_PU100KOHM | PAD_CTL_DSE_3P3V_49OHM)

#define ENET_PAD_CTRL_MII  (PAD_CTL_DSE_3P3V_32OHM)

#define SPI_PAD_CTRL (PAD_CTL_HYS | PAD_CTL_DSE_3P3V_49OHM)

#define KPP_ROW_PAD_CTRL (PAD_CTL_PUS_PU100KOHM |	\
	PAD_CTL_DSE_3P3V_98OHM | 						\
	PAD_CTL_SRE_SLOW  | PAD_CTL_HYS )

#define KPP_COL_PAD_CTRL (PAD_CTL_DSE_3P3V_32OHM |	\
	PAD_CTL_SRE_SLOW  | PAD_CTL_HYS)

#define NAND_PAD_CTRL (PAD_CTL_DSE_3P3V_49OHM | PAD_CTL_SRE_SLOW | PAD_CTL_HYS)

#define NAND_PAD_READY0_CTRL (PAD_CTL_DSE_3P3V_49OHM | PAD_CTL_PUS_PU5KOHM)

#define WEIM_NOR_PAD_CTRL (PAD_CTL_DSE_3P3V_49OHM | PAD_CTL_SRE_SLOW | \
	PAD_CTL_PUS_PU100KOHM)

/* UART1 */
static iomux_v3_cfg_t const uart1_pads[] = {
	MX7D_PAD_UART1_TX_DATA__UART1_DCE_TX | MUX_PAD_CTRL(UART_PAD_CTRL),
	MX7D_PAD_UART1_RX_DATA__UART1_DCE_RX | MUX_PAD_CTRL(UART_PAD_CTRL),
};

/* UART2 */
static iomux_v3_cfg_t const uart2_pads[] = {
	MX7D_PAD_UART2_TX_DATA__UART2_DCE_TX | MUX_PAD_CTRL(UART_PAD_CTRL),
	MX7D_PAD_UART2_RX_DATA__UART2_DCE_RX | MUX_PAD_CTRL(UART_PAD_CTRL),
};

/* UART3 */
static iomux_v3_cfg_t const uart3_pads[] = {
	MX7D_PAD_GPIO1_IO09__UART3_DCE_TX | MUX_PAD_CTRL(UART_PAD_CTRL),
	MX7D_PAD_GPIO1_IO08__UART3_DCE_RX | MUX_PAD_CTRL(UART_PAD_CTRL),
	MX7D_PAD_UART3_CTS_B__UART3_DCE_CTS | MUX_PAD_CTRL(UART_PAD_CTRL),
	MX7D_PAD_UART3_RTS_B__UART3_DCE_RTS | MUX_PAD_CTRL(UART_PAD_CTRL),
};

/* UART5 */
static iomux_v3_cfg_t const uart5_pads[] = {
	MX7D_PAD_GPIO1_IO06__UART5_RX_DATA 	| MUX_PAD_CTRL(UART_PAD_CTRL),
	MX7D_PAD_GPIO1_IO07__UART5_TX_DATA 	| MUX_PAD_CTRL(UART_PAD_CTRL),
	MX7D_PAD_GPIO1_IO04__UART5_CTS_B 	| MUX_PAD_CTRL(UART_PAD_CTRL),
	MX7D_PAD_GPIO1_IO05__UART5_RTS_B 	| MUX_PAD_CTRL(UART_PAD_CTRL),
};

/* I2C1 */
static struct i2c_pads_info i2c_pad_info1 = {
	.scl = {
		.i2c_mode =  MX7D_PAD_I2C1_SCL__I2C1_SCL 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gpio_mode = MX7D_PAD_I2C1_SCL__GPIO4_IO8 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gp = IMX_GPIO_NR(4, 8),
	},
	.sda = {
		.i2c_mode = MX7D_PAD_I2C1_SDA__I2C1_SDA 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gpio_mode = MX7D_PAD_I2C1_SDA__GPIO4_IO9 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gp = IMX_GPIO_NR(4, 9),
	},
};

/* I2C2 for PMIC and EEPROM */
static struct i2c_pads_info i2c_pad_info2 = {
	.scl = {
		.i2c_mode =  MX7D_PAD_I2C2_SCL__I2C2_SCL 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gpio_mode = MX7D_PAD_I2C2_SCL__GPIO4_IO10 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gp = IMX_GPIO_NR(4, 10),
	},
	.sda = {
		.i2c_mode = MX7D_PAD_I2C2_SDA__I2C2_SDA 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gpio_mode = MX7D_PAD_I2C2_SDA__GPIO4_IO11 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gp = IMX_GPIO_NR(4, 11),
	},
};

/* I2C3 */
static struct i2c_pads_info i2c_pad_info3 = {
	.scl = {
		.i2c_mode =  MX7D_PAD_I2C3_SCL__I2C3_SCL 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gpio_mode = MX7D_PAD_I2C3_SCL__GPIO4_IO12 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gp = IMX_GPIO_NR(4, 12),
	},
	.sda = {
		.i2c_mode = MX7D_PAD_I2C3_SDA__I2C3_SDA 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gpio_mode = MX7D_PAD_I2C3_SDA__GPIO4_IO13 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gp = IMX_GPIO_NR(4, 13),
	},
};

/* I2C4 */
static struct i2c_pads_info i2c_pad_info4 = {
	.scl = {
		.i2c_mode =  MX7D_PAD_I2C4_SCL__I2C4_SCL 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gpio_mode = MX7D_PAD_I2C4_SCL__GPIO4_IO14 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gp = IMX_GPIO_NR(4, 14),
	},
	.sda = {
		.i2c_mode = MX7D_PAD_I2C4_SDA__I2C4_SDA 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gpio_mode = MX7D_PAD_I2C4_SDA__GPIO4_IO15 	| MUX_PAD_CTRL(I2C_PAD_CTRL),
		.gp = IMX_GPIO_NR(4, 15),
	},
};

/* SD1 micro SD */
static iomux_v3_cfg_t const sd1_pads[] = {
	MX7D_PAD_SD1_CLK__SD1_CLK 		| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD1_CMD__SD1_CMD 		| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD1_DATA0__SD1_DATA0 	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD1_DATA1__SD1_DATA1 	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD1_DATA2__SD1_DATA2 	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD1_DATA3__SD1_DATA3 	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
	MX7D_PAD_SD1_CD_B__GPIO5_IO0	| MUX_PAD_CTRL(USDHC_PAD_CTRL),
};

/* NAND */
static iomux_v3_cfg_t const nand_pads[] = {
	MX7D_PAD_SD3_CLK__NAND_CLE			| MUX_PAD_CTRL(NAND_PAD_CTRL),
	MX7D_PAD_SD3_CMD__NAND_ALE 			| MUX_PAD_CTRL(NAND_PAD_CTRL),
	MX7D_PAD_SD3_DATA0__NAND_DATA00 	| MUX_PAD_CTRL(NAND_PAD_CTRL),
	MX7D_PAD_SD3_DATA1__NAND_DATA01 	| MUX_PAD_CTRL(NAND_PAD_CTRL),
	MX7D_PAD_SD3_DATA2__NAND_DATA02 	| MUX_PAD_CTRL(NAND_PAD_CTRL),
	MX7D_PAD_SD3_DATA3__NAND_DATA03 	| MUX_PAD_CTRL(NAND_PAD_CTRL),
	MX7D_PAD_SD3_DATA4__NAND_DATA04 	| MUX_PAD_CTRL(NAND_PAD_CTRL),
	MX7D_PAD_SD3_DATA5__NAND_DATA05 	| MUX_PAD_CTRL(NAND_PAD_CTRL),
	MX7D_PAD_SD3_DATA6__NAND_DATA06 	| MUX_PAD_CTRL(NAND_PAD_CTRL),
	MX7D_PAD_SD3_DATA7__NAND_DATA07 	| MUX_PAD_CTRL(NAND_PAD_CTRL),
	MX7D_PAD_SD3_STROBE__NAND_RE_B		| MUX_PAD_CTRL(NAND_PAD_CTRL),
	MX7D_PAD_SD3_RESET_B__NAND_WE_B		| MUX_PAD_CTRL(NAND_PAD_CTRL),
	MX7D_PAD_SAI1_TX_BCLK__NAND_CE0_B	| MUX_PAD_CTRL(NAND_PAD_CTRL),
	MX7D_PAD_SAI1_TX_DATA__NAND_READY_B	| MUX_PAD_CTRL(NAND_PAD_READY0_CTRL),
	MX7D_PAD_SAI1_MCLK__NAND_WP_B		| MUX_PAD_CTRL(NAND_PAD_CTRL),
};

static iomux_v3_cfg_t const can_pads[] = {
	MX7D_PAD_GPIO1_IO15__FLEXCAN2_TX | MUX_MODE_SION,
	MX7D_PAD_GPIO1_IO14__FLEXCAN2_RX | MUX_MODE_SION,
	MX7D_PAD_GPIO1_IO13__FLEXCAN1_TX | MUX_MODE_SION,
	MX7D_PAD_GPIO1_IO12__FLEXCAN1_RX | MUX_MODE_SION,
};

/* ECSPI1 For Expansion Connector */
static iomux_v3_cfg_t const ecspi1_pads[] = {
	MX7D_PAD_ECSPI1_SCLK__ECSPI1_SCLK 	| MUX_PAD_CTRL(SPI_PAD_CTRL),
	MX7D_PAD_ECSPI1_SS0__GPIO4_IO19 	| MUX_PAD_CTRL(SPI_PAD_CTRL) | MUX_MODE_SION, // SS0
	MX7D_PAD_ECSPI1_MOSI__ECSPI1_MOSI 	| MUX_PAD_CTRL(SPI_PAD_CTRL),
	MX7D_PAD_ECSPI1_MISO__ECSPI1_MISO 	| MUX_PAD_CTRL(SPI_PAD_CTRL),
};

/* ECSPI2 On Module SPI NOR Flash for Bootloader */
static iomux_v3_cfg_t const ecspi2_pads[] = {
	MX7D_PAD_ECSPI2_SCLK__ECSPI2_SCLK 	| MUX_PAD_CTRL(SPI_PAD_CTRL),
	MX7D_PAD_ECSPI2_SS0__GPIO4_IO23 	| MUX_PAD_CTRL(SPI_PAD_CTRL) | MUX_MODE_SION, // SS0
	MX7D_PAD_ECSPI2_MOSI__ECSPI2_MOSI	| MUX_PAD_CTRL(SPI_PAD_CTRL),
	MX7D_PAD_ECSPI2_MISO__ECSPI2_MISO 	| MUX_PAD_CTRL(SPI_PAD_CTRL),
};

/* ECSPI4 For Expansion Connector */
static iomux_v3_cfg_t const ecspi4_pads[] = {
	MX7D_PAD_SD1_RESET_B__ECSPI4_SCLK 	| MUX_PAD_CTRL(SPI_PAD_CTRL),
	MX7D_PAD_LCD_VSYNC__GPIO3_IO3 		| MUX_PAD_CTRL(SPI_PAD_CTRL) | MUX_MODE_SION, // SS0
	MX7D_PAD_LCD_ENABLE__ECSPI4_MOSI 	| MUX_PAD_CTRL(SPI_PAD_CTRL),
	MX7D_PAD_LCD_CLK__ECSPI4_MISO 		| MUX_PAD_CTRL(SPI_PAD_CTRL),
};

/* SAI2 audio interface for SGTL5000 codec */
static iomux_v3_cfg_t const audio_pads[] = {
	MX7D_PAD_SAI2_RX_DATA__SAI2_RX_DATA0 	| MUX_PAD_CTRL(AUDIO_PAD_CTRL),
	MX7D_PAD_SAI2_TX_DATA__SAI2_TX_DATA0 	| MUX_PAD_CTRL(AUDIO_PAD_CTRL),
	MX7D_PAD_SAI2_TX_SYNC__SAI2_TX_SYNC 	| MUX_PAD_CTRL(AUDIO_PAD_CTRL),
	MX7D_PAD_SAI2_TX_BCLK__SAI2_TX_BCLK 	| MUX_PAD_CTRL(AUDIO_PAD_CTRL),
	MX7D_PAD_SD2_RESET_B__SAI2_MCLK 		| MUX_PAD_CTRL(AUDIO_PAD_CTRL),
};

/* MDIO */
static iomux_v3_cfg_t const mdio_pads[] = {
	MX7D_PAD_GPIO1_IO10__ENET1_MDIO 				| MUX_PAD_CTRL(ENET_PAD_CTRL_MII),
	MX7D_PAD_GPIO1_IO11__ENET1_MDC 					| MUX_PAD_CTRL(ENET_PAD_CTRL_MII),
};

/* RGMII1 */
static iomux_v3_cfg_t const enet1_pads[] = {
	MX7D_PAD_ENET1_RGMII_RXC__ENET1_RGMII_RXC 		| MUX_PAD_CTRL(ENET_RX_PAD_CTRL),
	MX7D_PAD_ENET1_RGMII_RX_CTL__ENET1_RGMII_RX_CTL | MUX_PAD_CTRL(ENET_RX_PAD_CTRL),
	MX7D_PAD_ENET1_RGMII_TXC__ENET1_RGMII_TXC 		| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX7D_PAD_ENET1_RGMII_TX_CTL__ENET1_RGMII_TX_CTL | MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX7D_PAD_ENET1_RGMII_TD0__ENET1_RGMII_TD0 		| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX7D_PAD_ENET1_RGMII_TD1__ENET1_RGMII_TD1 		| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX7D_PAD_ENET1_RGMII_TD2__ENET1_RGMII_TD2 		| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX7D_PAD_ENET1_RGMII_TD3__ENET1_RGMII_TD3 		| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX7D_PAD_ENET1_RGMII_RD0__ENET1_RGMII_RD0 		| MUX_PAD_CTRL(ENET_RX_PAD_CTRL),
	MX7D_PAD_ENET1_RGMII_RD1__ENET1_RGMII_RD1 		| MUX_PAD_CTRL(ENET_RX_PAD_CTRL),
	MX7D_PAD_ENET1_RGMII_RD2__ENET1_RGMII_RD2 		| MUX_PAD_CTRL(ENET_RX_PAD_CTRL),
	MX7D_PAD_ENET1_RGMII_RD3__ENET1_RGMII_RD3 		| MUX_PAD_CTRL(ENET_RX_PAD_CTRL),
	MX7D_PAD_SAI1_RX_SYNC__GPIO6_IO16 				| MUX_PAD_CTRL(DIO_PDOWN_PAD_CTRL),	// ENET1_nRST
	MX7D_PAD_SAI1_RX_DATA__GPIO6_IO12 				| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),  // ENET1_nINT
};

/* RGMII2 - shared with EIM - depends on module options */
static iomux_v3_cfg_t const enet2_pads[] = {
	MX7D_PAD_EPDC_SDCE1__ENET2_RGMII_RXC 			| MUX_PAD_CTRL(ENET_RX_PAD_CTRL),
	MX7D_PAD_EPDC_SDCE0__ENET2_RGMII_RX_CTL 		| MUX_PAD_CTRL(ENET_RX_PAD_CTRL),
	MX7D_PAD_EPDC_GDSP__ENET2_RGMII_TXC 			| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX7D_PAD_EPDC_GDRL__ENET2_RGMII_TX_CTL 			| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX7D_PAD_EPDC_SDCE2__ENET2_RGMII_TD0 			| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX7D_PAD_EPDC_SDCE3__ENET2_RGMII_TD1 			| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX7D_PAD_EPDC_GDCLK__ENET2_RGMII_TD2 			| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX7D_PAD_EPDC_GDOE__ENET2_RGMII_TD3 			| MUX_PAD_CTRL(ENET_PAD_CTRL),
	MX7D_PAD_EPDC_SDCLK__ENET2_RGMII_RD0 			| MUX_PAD_CTRL(ENET_RX_PAD_CTRL),
	MX7D_PAD_EPDC_SDLE__ENET2_RGMII_RD1 			| MUX_PAD_CTRL(ENET_RX_PAD_CTRL),
	MX7D_PAD_EPDC_SDOE__ENET2_RGMII_RD2 			| MUX_PAD_CTRL(ENET_RX_PAD_CTRL),
	MX7D_PAD_EPDC_SDSHR__ENET2_RGMII_RD3 			| MUX_PAD_CTRL(ENET_RX_PAD_CTRL),
	MX7D_PAD_SAI1_TX_SYNC__GPIO6_IO14 				| MUX_PAD_CTRL(DIO_PDOWN_PAD_CTRL),	// ENET2_nRST
	MX7D_PAD_SAI1_RX_BCLK__GPIO6_IO17 				| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),  // ENET2_nINT
};

static iomux_v3_cfg_t const eim_pads[] = {
	MX7D_PAD_LCD_DATA00__EIM_DATA0 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA01__EIM_DATA1 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA02__EIM_DATA2 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA03__EIM_DATA3 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA04__EIM_DATA4 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA05__EIM_DATA5 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA06__EIM_DATA6 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA07__EIM_DATA7 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA08__EIM_DATA8 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA09__EIM_DATA9 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA10__EIM_DATA10 	| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA11__EIM_DATA11 	| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA12__EIM_DATA12 	| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA13__EIM_DATA13 	| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA14__EIM_DATA14 	| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA15__EIM_DATA15 	| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_DATA00__EIM_AD0 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_DATA01__EIM_AD1 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_DATA02__EIM_AD2		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_DATA03__EIM_AD3 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_DATA04__EIM_AD4 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_DATA05__EIM_AD5 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_DATA06__EIM_AD6 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_DATA07__EIM_AD7 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_BDR1__EIM_AD8 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_PWR_COM__EIM_AD9 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_SDCLK__EIM_AD10 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_SDLE__EIM_AD11 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_SDOE__EIM_AD12 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_SDSHR__EIM_AD13 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_SDCE0__EIM_AD14 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_SDCE1__EIM_AD15 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_SDCE2__EIM_ADDR16 	| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_SDCE3__EIM_ADDR17 	| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_GDCLK__EIM_ADDR18 	| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_GDOE__EIM_ADDR19 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_GDRL__EIM_ADDR20 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_GDSP__EIM_ADDR21 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_BDR0__EIM_ADDR22 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA20__EIM_ADDR23 	| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA21__EIM_ADDR24 	| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA22__EIM_ADDR25 	| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA23__EIM_ADDR26 	| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_DATA08__EIM_OE 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_DATA09__EIM_RW 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_DATA11__EIM_BCLK 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_DATA12__EIM_LBA_B 	| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_DATA13__EIM_WAIT 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_DATA14__EIM_EB_B0 	| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_PWR_STAT__EIM_EB_B1 	| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA16__EIM_CRE 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_DATA10__EIM_CS0_B 	| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_EPDC_DATA15__EIM_CS1_B 	| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA18__EIM_CS2_B 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
	MX7D_PAD_LCD_DATA19__EIM_CS3_B 		| MUX_PAD_CTRL(WEIM_NOR_PAD_CTRL),
};

static iomux_v3_cfg_t const eim_gpio_pads[] = {
	MX7D_PAD_LCD_DATA00__GPIO3_IO5 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA01__GPIO3_IO6 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA02__GPIO3_IO7 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA03__GPIO3_IO8 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA04__GPIO3_IO9 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA05__GPIO3_IO10 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA06__GPIO3_IO11 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA07__GPIO3_IO12 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA08__GPIO3_IO13 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA09__GPIO3_IO14 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA10__GPIO3_IO15 	| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA11__GPIO3_IO16 	| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA12__GPIO3_IO17 	| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA13__GPIO3_IO18 	| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA14__GPIO3_IO19 	| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA15__GPIO3_IO20 	| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_EPDC_DATA00__GPIO2_IO0 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_EPDC_DATA01__GPIO2_IO1 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_EPDC_DATA02__GPIO2_IO2		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_EPDC_DATA03__GPIO2_IO3 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_EPDC_DATA04__GPIO2_IO4 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_EPDC_DATA05__GPIO2_IO5 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_EPDC_DATA06__GPIO2_IO6 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_EPDC_DATA07__GPIO2_IO7 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_EPDC_BDR1__GPIO2_IO29 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_EPDC_PWR_COM__GPIO2_IO30 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_EPDC_BDR0__GPIO2_IO28 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA20__GPIO3_IO25 	| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA21__GPIO3_IO26 	| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA22__GPIO3_IO27 	| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA23__GPIO3_IO28 	| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_EPDC_DATA08__GPIO2_IO8 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_EPDC_DATA09__GPIO2_IO9 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_EPDC_DATA11__GPIO2_IO11 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_EPDC_DATA12__GPIO2_IO12 	| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_EPDC_DATA13__GPIO2_IO13 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_EPDC_DATA14__GPIO2_IO14 	| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_EPDC_PWR_STAT__GPIO2_IO31 	| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA16__GPIO3_IO21 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_EPDC_DATA10__GPIO2_IO10 	| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_EPDC_DATA15__GPIO2_IO15 	| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA18__GPIO3_IO23 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
	MX7D_PAD_LCD_DATA19__GPIO3_IO24 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL),
};

static iomux_v3_cfg_t const eeprom_pads[] = {
	MX7D_PAD_SD2_CD_B__GPIO5_IO9	| MUX_PAD_CTRL(DIO_PDOWN_PAD_CTRL),
};

static iomux_v3_cfg_t const spinor_pads[] = {
	MX7D_PAD_SD2_WP__GPIO5_IO10		| MUX_PAD_CTRL(DIO_PDOWN_PAD_CTRL),
};

static iomux_v3_cfg_t const pwm_pads[] = {
	MX7D_PAD_GPIO1_IO01__PWM1_OUT	| MUX_PAD_CTRL(NO_PAD_CTRL),
};

static iomux_v3_cfg_t const ccm_pads[] = {
	MX7D_PAD_GPIO1_IO02__CCM_CLKO1 	| MUX_PAD_CTRL(NO_PAD_CTRL),
	MX7D_PAD_GPIO1_IO03__CCM_CLKO2 	| MUX_PAD_CTRL(NO_PAD_CTRL),
};

static iomux_v3_cfg_t const gpio_pads[] = {
	MX7D_PAD_ENET1_TX_CLK__GPIO7_IO12	| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL), 	// PMIC_nINT
	MX7D_PAD_ENET1_COL__GPIO7_IO15 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL), 	// RTC_nINT
	MX7D_PAD_ENET1_CRS__GPIO7_IO14 		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL), 	// DSI-IRQ
	MX7D_PAD_SD2_CMD__GPIO5_IO13		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL), 	// PCIe WAKE
	MX7D_PAD_SD2_CLK__GPIO5_IO12		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL), 	// PCIe CLKREQ
	MX7D_PAD_LCD_HSYNC__GPIO3_IO2		| MUX_PAD_CTRL(DIO_PDOWN_PAD_CTRL), // GPIO su CN2
	MX7D_PAD_SD2_DATA2__GPIO5_IO16		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL), 	// SX1509 nINT
	MX7D_PAD_SD2_DATA3__GPIO5_IO17		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL), 	// SX1509 nRESET
};

static iomux_v3_cfg_t const usb_otg1_pads[] = {
	MX7D_PAD_UART3_TX_DATA__USB_OTG1_PWR 	| MUX_PAD_CTRL(DIO_PDOWN_PAD_CTRL), // USB_OTG1_PWR
	MX7D_PAD_UART3_RX_DATA__USB_OTG1_OC		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL), 	// USB_OTG1_nOC
};

static iomux_v3_cfg_t const usb_otg2_pads[] = {
	MX7D_PAD_LCD_RESET__GPIO3_IO4		| MUX_PAD_CTRL(DIO_PDOWN_PAD_CTRL), // USB-OTG2-SEL
	MX7D_PAD_SD1_WP__GPIO5_IO1			| MUX_PAD_CTRL(DIO_PDOWN_PAD_CTRL), // USB-OTG2-nOE
	MX7D_PAD_SD2_DATA0__GPIO5_IO14 		| MUX_PAD_CTRL(DIO_PDOWN_PAD_CTRL), // USB_OTG2_PWR
	MX7D_PAD_SD2_DATA1__GPIO5_IO15		| MUX_PAD_CTRL(DIO_PUP_PAD_CTRL), 	// USB_OTG2_nOC
};

static iomux_v3_cfg_t const wd_pads[] = {
	MX7D_PAD_GPIO1_IO00__WDOG1_WDOG_B	| MUX_PAD_CTRL(NO_PAD_CTRL),
};

static void my_uart_console_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(uart1_pads, ARRAY_SIZE(uart1_pads));
}

static void my_uart_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(uart2_pads, ARRAY_SIZE(uart2_pads));
	imx_iomux_v3_setup_multiple_pads(uart3_pads, ARRAY_SIZE(uart3_pads));
	imx_iomux_v3_setup_multiple_pads(uart5_pads, ARRAY_SIZE(uart5_pads));
}

static void my_eeprom_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(eeprom_pads, ARRAY_SIZE(eeprom_pads));
}

static void my_i2c_init_mux(void)
{
	setup_i2c(0, CONFIG_SYS_I2C_SPEED, 0x7f, &i2c_pad_info1);
	setup_i2c(1, CONFIG_SYS_I2C_SPEED, 0x7f, &i2c_pad_info2);
	setup_i2c(2, CONFIG_SYS_I2C_SPEED, 0x7f, &i2c_pad_info3);
	setup_i2c(3, CONFIG_SYS_I2C_SPEED, 0x7f, &i2c_pad_info4);
}

static void my_sdio_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(sd1_pads, ARRAY_SIZE(sd1_pads));
}

static void my_nand_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(nand_pads, ARRAY_SIZE(nand_pads));
}

static void my_can_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(can_pads, ARRAY_SIZE(can_pads));
}

static void my_nor_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(spinor_pads, ARRAY_SIZE(spinor_pads));
	/* Default: write protect active on spi nor */
	gpio_direction_output(IMX_GPIO_NR(5,10), 1);
}

static void my_ecspi_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(ecspi1_pads, ARRAY_SIZE(ecspi1_pads));
	imx_iomux_v3_setup_multiple_pads(ecspi2_pads, ARRAY_SIZE(ecspi2_pads));
	imx_iomux_v3_setup_multiple_pads(ecspi4_pads, ARRAY_SIZE(ecspi4_pads));
}

static void my_audio_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(audio_pads, ARRAY_SIZE(audio_pads));
}

static void my_enet1_init_mux(void)
{

	imx_iomux_v3_setup_multiple_pads(mdio_pads, ARRAY_SIZE(mdio_pads));
	imx_iomux_v3_setup_multiple_pads(enet1_pads, ARRAY_SIZE(enet1_pads));
}

static void my_enet2_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(mdio_pads, ARRAY_SIZE(mdio_pads));
	imx_iomux_v3_setup_multiple_pads(enet2_pads, ARRAY_SIZE(enet2_pads));
}

static void my_eim_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(eim_pads, ARRAY_SIZE(eim_pads));
}

static void my_eim_gpio_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(eim_gpio_pads, ARRAY_SIZE(eim_gpio_pads));
}

static void my_pwm_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(pwm_pads, ARRAY_SIZE(pwm_pads));
}

static void my_ccm_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(ccm_pads, ARRAY_SIZE(ccm_pads));
}

static void my_gpio_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(gpio_pads, ARRAY_SIZE(gpio_pads));
	/* Deassert SX1509 GPIO Expander Reset */
	gpio_direction_output(IMX_GPIO_NR(5,17), 1);
}

static void my_usb_otg1_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(usb_otg1_pads, ARRAY_SIZE(usb_otg1_pads));
}

static void my_usb_otg2_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(usb_otg2_pads, ARRAY_SIZE(usb_otg2_pads));
	gpio_direction_output(IMX_GPIO_NR(5,14), 1); // Enable VBUS for host port
	gpio_direction_output(IMX_GPIO_NR(3,4), 0); // Enable OTG2 for USB connector
	gpio_direction_output(IMX_GPIO_NR(5,1), 0); // Enable OTG2 for USB connector
}

static void my_wd_init_mux(void)
{
	imx_iomux_v3_setup_multiple_pads(wd_pads, ARRAY_SIZE(wd_pads));
}

void egf_common_mux_init(void)
{
	my_uart_console_init_mux();
	my_i2c_init_mux();
	my_ecspi_init_mux();
	my_eeprom_init_mux();
	my_nor_init_mux();
	my_uart_init_mux();
	my_wd_init_mux();
	my_can_init_mux();
	my_audio_init_mux();
	my_ccm_init_mux();
	my_gpio_init_mux();
	my_sdio_init_mux();
	my_usb_otg1_init_mux();
	my_usb_otg2_init_mux();
	my_pwm_init_mux();
}

void egf_mux_init_wid0575_aa0101(void)
{
	my_enet1_init_mux();
	my_enet2_init_mux();
	my_nand_init_mux();
	my_eim_gpio_init_mux();
}

void egf_mux_init_wid0575_ab0101(void)
{
	my_enet1_init_mux();
	my_nand_init_mux();
	my_eim_init_mux();
}




