#include "gf_mux.h"

#include <common.h>
#include <i2c.h>
#include <asm/io.h>
#include <asm/gpio.h>
#include <asm/arch/iomux.h>
#include <asm/arch/mx6-pins.h>
#include <asm/arch/crm_regs.h>
#include <asm/arch/sys_proto.h>
#include <asm/imx-common/boot_mode.h>
#include <asm/imx-common/iomux-v3.h>
#include <asm/imx-common/mxc_i2c.h>

#define HDMI_CEC_PAD_CTRL (PAD_CTL_PUS_22K_UP |	\
	PAD_CTL_DSE_40ohm | PAD_CTL_ODE |			\
	PAD_CTL_SRE_SLOW  | PAD_CTL_HYS | 			\
	PAD_CTL_SPEED_MED)

#define KPP_ROW_PAD_CTRL (PAD_CTL_PUS_100K_UP |	\
	PAD_CTL_DSE_120ohm | 						\
	PAD_CTL_SRE_SLOW  | PAD_CTL_HYS)

#define KPP_COL_PAD_CTRL (PAD_CTL_PKE |			\
	PAD_CTL_DSE_40ohm | PAD_CTL_SPEED_MED |		\
	PAD_CTL_SRE_SLOW  | PAD_CTL_HYS)

#define AUDIO_PAD_CTRL (PAD_CTL_PUS_100K_DOWN | 	\
	PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm | 		\
	PAD_CTL_SRE_SLOW | PAD_CTL_HYS)

#define UART_PAD_CTRL  (PAD_CTL_PUS_100K_UP |			\
	PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm |			\
	PAD_CTL_SRE_FAST  | PAD_CTL_HYS)

#define USDHC_PAD_CTRL (PAD_CTL_PUS_47K_UP |			\
	PAD_CTL_SPEED_LOW | PAD_CTL_DSE_80ohm |			\
	PAD_CTL_SRE_FAST  | PAD_CTL_HYS)

//DSE(110) = 32 Ohm @ 3.3V
#define USDHC_PAD_CLK_CTRL (PAD_CTL_PUS_47K_UP |			\
	PAD_CTL_SPEED_LOW | (6 << 3) |			\
	PAD_CTL_SRE_FAST  | PAD_CTL_HYS)

#define ENET_PAD_CTRL  (PAD_CTL_PUS_100K_UP |			\
	PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm | PAD_CTL_HYS)

#define SPI_PAD_CTRL (PAD_CTL_HYS | PAD_CTL_SPEED_MED | \
		      PAD_CTL_DSE_40ohm | PAD_CTL_SRE_FAST)

#define I2C_PAD_CTRL  (PAD_CTL_PUS_100K_UP |                    \
	PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm | PAD_CTL_HYS |   \
	PAD_CTL_ODE | PAD_CTL_SRE_FAST)
#define I2CPC MUX_PAD_CTRL(I2C_PAD_CTRL)
#define CONFIG_SYS_I2C_SPEED	100000

#define DIO_PAD_CTRL  (PAD_CTL_PKE | PAD_CTL_PUE |		\
	PAD_CTL_PUS_100K_UP | PAD_CTL_SPEED_MED |		\
	PAD_CTL_DSE_34ohm | PAD_CTL_HYS | PAD_CTL_SRE_FAST)
#define DIO_PAD_CFG   (MUX_PAD_CTRL(DIO_PAD_CTRL) | MUX_MODE_SION)
#define USBH1_PAD_NO_PULL_CFG   (MUX_PAD_CTRL(PAD_CTL_PKE |	 PAD_CTL_SPEED_MED |	\
								  PAD_CTL_DSE_34ohm | PAD_CTL_HYS | PAD_CTL_SRE_FAST) | MUX_MODE_SION)

#define DIO_PAD_PDOWN_CTRL  (PAD_CTL_PKE | PAD_CTL_PUE |		\
	PAD_CTL_PUS_100K_DOWN | PAD_CTL_SPEED_MED |		\
	PAD_CTL_DSE_34ohm | PAD_CTL_HYS | PAD_CTL_SRE_FAST)
#define DIO_PAD_PDOWN_CFG   (MUX_PAD_CTRL(DIO_PAD_PDOWN_CTRL) | MUX_MODE_SION)

#define DIO_PDOWN_PAD_CTRL  (PAD_CTL_PKE | PAD_CTL_PUE |		\
	PAD_CTL_PUS_100K_DOWN | PAD_CTL_SPEED_MED |		\
	PAD_CTL_DSE_34ohm | PAD_CTL_HYS | PAD_CTL_SRE_FAST)
#define DIO_PDOWN_PAD_CFG   (MUX_PAD_CTRL(DIO_PDOWN_PAD_CTRL) | MUX_MODE_SION)

#define DIO_PUP_PAD_CTRL  (PAD_CTL_PKE | PAD_CTL_PUE |		\
	PAD_CTL_PUS_100K_UP | PAD_CTL_SPEED_MED |		\
	PAD_CTL_DSE_34ohm | PAD_CTL_HYS | PAD_CTL_SRE_FAST)
#define DIO_PUP_PAD_CFG   (MUX_PAD_CTRL(DIO_PUP_PAD_CTRL) | MUX_MODE_SION)

#define GPMI_PAD_CTRL0 (PAD_CTL_PKE | PAD_CTL_PUE | PAD_CTL_PUS_100K_UP)
#define GPMI_PAD_CTRL1 (PAD_CTL_DSE_40ohm | PAD_CTL_SPEED_MED | \
			PAD_CTL_SRE_FAST)
#define GPMI_PAD_CTRL2 (GPMI_PAD_CTRL0 | GPMI_PAD_CTRL1)

#define NO_PAD_CTRL_SION_CFG	(MUX_PAD_CTRL(NO_PAD_CTRL) | MUX_MODE_SION)
#define DISP_PAD_CTRL			(0x10)
#define PWM_PAD_CTRL			(0x1b0b1)

/* UART1 RS-232*/
static iomux_v3_cfg_t const mx6_uart1_pads[] = {
	IOMUX_PADS(PAD_CSI0_DAT10__UART1_TX_DATA | MUX_PAD_CTRL(UART_PAD_CTRL)),
	IOMUX_PADS(PAD_CSI0_DAT11__UART1_RX_DATA | MUX_PAD_CTRL(UART_PAD_CTRL)),
	IOMUX_PADS(PAD_EIM_D19__UART1_CTS_B | MUX_PAD_CTRL(UART_PAD_CTRL)),
	IOMUX_PADS(PAD_EIM_D20__UART1_RTS_B | MUX_PAD_CTRL(UART_PAD_CTRL)),
};

/* UART2 RS-232*/
static iomux_v3_cfg_t const mx6_uart2_pads[] = {
	IOMUX_PADS(PAD_SD4_DAT7__UART2_TX_DATA | MUX_PAD_CTRL(UART_PAD_CTRL)),
	IOMUX_PADS(PAD_SD4_DAT4__UART2_RX_DATA | MUX_PAD_CTRL(UART_PAD_CTRL)),
	IOMUX_PADS(PAD_SD4_DAT6__UART2_CTS_B | MUX_PAD_CTRL(UART_PAD_CTRL)),
	IOMUX_PADS(PAD_SD4_DAT5__UART2_RTS_B | MUX_PAD_CTRL(UART_PAD_CTRL)),
};

/* UART3 -> BT+BLE */
static iomux_v3_cfg_t const mx6_uart3_pads[] = {
	IOMUX_PADS(PAD_EIM_D24__UART3_TX_DATA | MUX_PAD_CTRL(UART_PAD_CTRL)),
	IOMUX_PADS(PAD_EIM_D25__UART3_RX_DATA | MUX_PAD_CTRL(UART_PAD_CTRL)),
	IOMUX_PADS(PAD_EIM_D23__UART3_CTS_B | MUX_PAD_CTRL(UART_PAD_CTRL)),
	IOMUX_PADS(PAD_EIM_D31__UART3_RTS_B | MUX_PAD_CTRL(UART_PAD_CTRL)),
};

/* UART5 -> 485 */
static iomux_v3_cfg_t const mx6_uart5_pads[] = {
	IOMUX_PADS(PAD_CSI0_DAT14__UART5_TX_DATA | MUX_PAD_CTRL(UART_PAD_CTRL)),
	IOMUX_PADS(PAD_CSI0_DAT15__UART5_RX_DATA | MUX_PAD_CTRL(UART_PAD_CTRL)),
	IOMUX_PADS(PAD_CSI0_DAT19__UART5_CTS_B | MUX_PAD_CTRL(UART_PAD_CTRL)),
};

static void my_uart_init_mux(void)
{
	SETUP_IOMUX_PADS(mx6_uart1_pads);
	SETUP_IOMUX_PADS(mx6_uart2_pads);
	SETUP_IOMUX_PADS(mx6_uart3_pads);
	SETUP_IOMUX_PADS(mx6_uart5_pads);
}

/* I2C1 */
static struct i2c_pads_info mx6q_i2c_pad_info0 = {
	.scl = {
		.i2c_mode = MX6Q_PAD_CSI0_DAT9__I2C1_SCL | I2CPC,
		.gpio_mode = MX6Q_PAD_CSI0_DAT9__GPIO5_IO27 | I2CPC,
		.gp = IMX_GPIO_NR(5, 27)
	},
	.sda = {
		.i2c_mode = MX6Q_PAD_CSI0_DAT8__I2C1_SDA | I2CPC,
		.gpio_mode = MX6Q_PAD_CSI0_DAT8__GPIO5_IO26 | I2CPC,
		.gp = IMX_GPIO_NR(5, 26)
	}
};

static struct i2c_pads_info mx6dl_i2c_pad_info0 = {
	.scl = {
		.i2c_mode = MX6DL_PAD_CSI0_DAT9__I2C1_SCL | I2CPC,
		.gpio_mode = MX6DL_PAD_CSI0_DAT9__GPIO5_IO27 | I2CPC,
		.gp = IMX_GPIO_NR(5, 27)
	},
	.sda = {
		.i2c_mode = MX6DL_PAD_CSI0_DAT8__I2C1_SDA | I2CPC,
		.gpio_mode = MX6DL_PAD_CSI0_DAT8__GPIO5_IO26 | I2CPC,
		.gp = IMX_GPIO_NR(5, 26)
	}
};

/* I2C2 */
static struct i2c_pads_info mx6q_i2c_pad_info1 = {
	.scl = {
		.i2c_mode = MX6Q_PAD_EIM_EB2__I2C2_SCL | I2CPC,
		.gpio_mode = MX6Q_PAD_EIM_EB2__GPIO2_IO30 | I2CPC,
		.gp = IMX_GPIO_NR(2, 30)
	},
	.sda = {
		.i2c_mode = MX6Q_PAD_EIM_D16__I2C2_SDA | I2CPC,
		.gpio_mode = MX6Q_PAD_EIM_D16__GPIO3_IO16 | I2CPC,
		.gp = IMX_GPIO_NR(3, 16)
	}
};

static struct i2c_pads_info mx6dl_i2c_pad_info1 = {
	.scl = {
		.i2c_mode = MX6DL_PAD_EIM_EB2__I2C2_SCL | I2CPC,
		.gpio_mode = MX6DL_PAD_EIM_EB2__GPIO2_IO30 | I2CPC,
		.gp = IMX_GPIO_NR(2, 30)
	},
	.sda = {
		.i2c_mode = MX6DL_PAD_EIM_D16__I2C2_SDA | I2CPC,
		.gpio_mode = MX6DL_PAD_EIM_D16__GPIO3_IO16 | I2CPC,
		.gp = IMX_GPIO_NR(3, 16)
	}
};

/* I2C3 */
static struct i2c_pads_info mx6q_i2c_pad_info2 = {
	.scl = {
		.i2c_mode = MX6Q_PAD_EIM_D17__I2C3_SCL | I2CPC,
		.gpio_mode = MX6Q_PAD_EIM_D17__GPIO3_IO17 | I2CPC,
		.gp = IMX_GPIO_NR(3, 17)
	},
	.sda = {
		.i2c_mode = MX6Q_PAD_EIM_D18__I2C3_SDA | I2CPC,
		.gpio_mode = MX6Q_PAD_EIM_D18__GPIO3_IO18 | I2CPC,
		.gp = IMX_GPIO_NR(3, 18)
	}
};

static struct i2c_pads_info mx6dl_i2c_pad_info2 = {
	.scl = {
		.i2c_mode = MX6DL_PAD_EIM_D17__I2C3_SCL | I2CPC,
		.gpio_mode = MX6DL_PAD_EIM_D17__GPIO3_IO17 | I2CPC,
		.gp = IMX_GPIO_NR(3, 17)
	},
	.sda = {
		.i2c_mode = MX6DL_PAD_EIM_D18__I2C3_SDA | I2CPC,
		.gpio_mode = MX6DL_PAD_EIM_D18__GPIO3_IO18 | I2CPC,
		.gp = IMX_GPIO_NR(3, 18)
	}
};

static void my_i2c_init_mux(void)
{
	if (is_cpu_type(MXC_CPU_MX6Q) || is_cpu_type(MXC_CPU_MX6D)) {
		setup_i2c(0, CONFIG_SYS_I2C_SPEED, 0x7f, &mx6q_i2c_pad_info0);
		setup_i2c(1, CONFIG_SYS_I2C_SPEED, 0x7f, &mx6q_i2c_pad_info1);
		setup_i2c(2, CONFIG_SYS_I2C_SPEED, 0x7f, &mx6q_i2c_pad_info2);
	}
	else {
		setup_i2c(0, CONFIG_SYS_I2C_SPEED, 0x7f, &mx6dl_i2c_pad_info0);
		setup_i2c(1, CONFIG_SYS_I2C_SPEED, 0x7f, &mx6dl_i2c_pad_info1);
		setup_i2c(2, CONFIG_SYS_I2C_SPEED, 0x7f, &mx6dl_i2c_pad_info2);
	}
}

/* ETHERNET */

static iomux_v3_cfg_t const mx6_enet_pads[] = {
	IOMUX_PADS(PAD_ENET_MDIO__ENET_MDIO			| MUX_PAD_CTRL(ENET_PAD_CTRL)),
	IOMUX_PADS(PAD_ENET_MDC__ENET_MDC			| MUX_PAD_CTRL(ENET_PAD_CTRL)),
	IOMUX_PADS(PAD_RGMII_TXC__RGMII_TXC			| MUX_PAD_CTRL(ENET_PAD_CTRL)),
	IOMUX_PADS(PAD_RGMII_TD0__RGMII_TD0			| MUX_PAD_CTRL(ENET_PAD_CTRL)),
	IOMUX_PADS(PAD_RGMII_TD1__RGMII_TD1			| MUX_PAD_CTRL(ENET_PAD_CTRL)),
	IOMUX_PADS(PAD_RGMII_TD2__RGMII_TD2			| MUX_PAD_CTRL(ENET_PAD_CTRL)),
	IOMUX_PADS(PAD_RGMII_TD3__RGMII_TD3			| MUX_PAD_CTRL(ENET_PAD_CTRL)),
	IOMUX_PADS(PAD_RGMII_TX_CTL__RGMII_TX_CTL	| MUX_PAD_CTRL(ENET_PAD_CTRL)),
	IOMUX_PADS(PAD_ENET_REF_CLK__ENET_TX_CLK	| MUX_PAD_CTRL(ENET_PAD_CTRL)),
	IOMUX_PADS(PAD_RGMII_RXC__RGMII_RXC			| MUX_PAD_CTRL(ENET_PAD_CTRL)),
	IOMUX_PADS(PAD_RGMII_RD0__RGMII_RD0			| MUX_PAD_CTRL(ENET_PAD_CTRL)),
	IOMUX_PADS(PAD_RGMII_RD1__RGMII_RD1			| MUX_PAD_CTRL(ENET_PAD_CTRL)),
	IOMUX_PADS(PAD_RGMII_RD2__RGMII_RD2			| MUX_PAD_CTRL(ENET_PAD_CTRL)),
	IOMUX_PADS(PAD_RGMII_RD3__RGMII_RD3			| MUX_PAD_CTRL(ENET_PAD_CTRL)),
	IOMUX_PADS(PAD_RGMII_RX_CTL__RGMII_RX_CTL	| MUX_PAD_CTRL(ENET_PAD_CTRL)),
	IOMUX_PADS(PAD_ENET_RXD1__GPIO1_IO26		| NO_PAD_CTRL_SION_CFG), // enet-int
	IOMUX_PADS(PAD_ENET_TX_EN__GPIO1_IO28		| DIO_PAD_CFG), // enable 3v3
	/* AR8031 PHY Reset */
	IOMUX_PADS(PAD_ENET_CRS_DV__GPIO1_IO25		| DIO_PAD_CFG),
};

static void my_enet_init_mux(void)
{
	SETUP_IOMUX_PADS(mx6_enet_pads);
}

/* ECSPI4*/
/* Notare che i chip select sono usati come GPIO e non nella
 * loro funzione nativa. La gestione nel kernel sembra diversa.
 * Fare riferimeno al driver mxc_spi.c in particolare alla funzione
 *
 * static int decode_cs(struct mxc_spi_slave *mxcs, unsigned int cs)
 *
 * La definizione del chip select  usato e' nel config
 * eg. #define CONFIG_SF_DEFAULT_CS		(0 | (IMX_GPIO_NR(3, 20) << 8))
 */
static iomux_v3_cfg_t const mx6_ecspi4_pads[] = {
	IOMUX_PADS(PAD_EIM_D21__ECSPI4_SCLK 	| MUX_PAD_CTRL(SPI_PAD_CTRL)),
	IOMUX_PADS(PAD_EIM_D22__ECSPI4_MISO		| MUX_PAD_CTRL(SPI_PAD_CTRL)),
	IOMUX_PADS(PAD_EIM_D28__ECSPI4_MOSI 	| MUX_PAD_CTRL(SPI_PAD_CTRL)),
};

static iomux_v3_cfg_t const spinor_pads[] = {
	IOMUX_PADS(PAD_EIM_A25__GPIO5_IO02  	| NO_PAD_CTRL_SION_CFG),	//CS 1 -> pullup 10K
	IOMUX_PADS(PAD_EIM_D26__GPIO3_IO26  	| NO_PAD_CTRL_SION_CFG),	//WP   -> pulldown 47K
};

static iomux_v3_cfg_t const mx6_ecspi2_pads[] = {
	IOMUX_PADS(PAD_EIM_OE__ECSPI2_MISO	| MUX_PAD_CTRL(SPI_PAD_CTRL)),
	IOMUX_PADS(PAD_EIM_CS1__ECSPI2_MOSI	| MUX_PAD_CTRL(SPI_PAD_CTRL)),
	IOMUX_PADS(PAD_EIM_CS0__ECSPI2_SCLK | MUX_PAD_CTRL(SPI_PAD_CTRL)),
	IOMUX_PADS(PAD_EIM_RW__GPIO2_IO26  	| NO_PAD_CTRL_SION_CFG),	//CS 0
};

/*
 * Touchscreen
 */
static iomux_v3_cfg_t const touch_pads[] = {
	IOMUX_PADS(PAD_EIM_D29__GPIO3_IO29  	| NO_PAD_CTRL_SION_CFG),//CS 0
	IOMUX_PADS(PAD_GPIO_16__GPIO7_IO11	| DIO_PAD_CFG), // TS_nINT - GPIO 203
	IOMUX_PADS(PAD_EIM_BCLK__GPIO6_IO31	| DIO_PAD_CFG), // TS_nRST - GPIO 191
	IOMUX_PADS(PAD_EIM_D27__GPIO3_IO27	| DIO_PAD_PDOWN_CFG), // TS_nATT - GPIO 91

};

static void my_spi4_init_mux(void)
{
	SETUP_IOMUX_PADS(mx6_ecspi4_pads);
}

static void my_spi2_init_mux(void)
{
	SETUP_IOMUX_PADS(mx6_ecspi2_pads);
}

static void my_spinor_init_mux(void)
{
	SETUP_IOMUX_PADS(spinor_pads);
}

static void my_touch_init_mux(void)
{
	SETUP_IOMUX_PADS(touch_pads);
	gpio_direction_output((IMX_GPIO_NR(6, 31)),1);
}
/* eMCC
 *
 * SD3 -> Interna al Modulo
 *
 * */
static iomux_v3_cfg_t const mx6_usdhc3_pads[] = {
	IOMUX_PADS(PAD_SD3_CLK__SD3_CLK   | MUX_PAD_CTRL(USDHC_PAD_CTRL)),
	IOMUX_PADS(PAD_SD3_CMD__SD3_CMD   | MUX_PAD_CTRL(USDHC_PAD_CTRL)),
	IOMUX_PADS(PAD_SD3_DAT0__SD3_DATA0 | MUX_PAD_CTRL(USDHC_PAD_CTRL)),
	IOMUX_PADS(PAD_SD3_DAT1__SD3_DATA1 | MUX_PAD_CTRL(USDHC_PAD_CTRL)),
	IOMUX_PADS(PAD_SD3_DAT2__SD3_DATA2 | MUX_PAD_CTRL(USDHC_PAD_CTRL)),
	IOMUX_PADS(PAD_SD3_DAT3__SD3_DATA3 | MUX_PAD_CTRL(USDHC_PAD_CTRL)),
	IOMUX_PADS(PAD_SD3_DAT4__SD3_DATA4 | MUX_PAD_CTRL(USDHC_PAD_CTRL)),
	IOMUX_PADS(PAD_SD3_DAT5__SD3_DATA5 | MUX_PAD_CTRL(USDHC_PAD_CTRL)),
	IOMUX_PADS(PAD_SD3_DAT6__SD3_DATA6 | MUX_PAD_CTRL(USDHC_PAD_CTRL)),
	IOMUX_PADS(PAD_SD3_DAT7__SD3_DATA7 | MUX_PAD_CTRL(USDHC_PAD_CTRL)),
	IOMUX_PADS(PAD_SD3_RST__SD3_RESET  | MUX_PAD_CTRL(NO_PAD_CTRL)), /* Segnale di Reset Gestito dal Bios */
};




static void my_emmc_init_mux(void)
{
	SETUP_IOMUX_PADS(mx6_usdhc3_pads);
}

static iomux_v3_cfg_t const wd_pads[] = {
	IOMUX_PADS(PAD_GPIO_1__WDOG2_B  	| MUX_PAD_CTRL(NO_PAD_CTRL)),
};

static void my_wd_init_mux(void)
{
	SETUP_IOMUX_PADS(wd_pads);
}

/* microSD
 *
 * SD1
 *
 * */

static iomux_v3_cfg_t const mx6_usdhc1_pads[] = {
	IOMUX_PADS(PAD_SD1_CLK__SD1_CLK			| MUX_PAD_CTRL(USDHC_PAD_CLK_CTRL)),
	IOMUX_PADS(PAD_SD1_CMD__SD1_CMD			| MUX_PAD_CTRL(USDHC_PAD_CTRL)),
	IOMUX_PADS(PAD_SD1_DAT0__SD1_DATA0		| MUX_PAD_CTRL(USDHC_PAD_CTRL)),
	IOMUX_PADS(PAD_SD1_DAT1__SD1_DATA1		| MUX_PAD_CTRL(USDHC_PAD_CTRL)),
	IOMUX_PADS(PAD_SD1_DAT2__SD1_DATA2		| MUX_PAD_CTRL(USDHC_PAD_CTRL)),
	IOMUX_PADS(PAD_SD1_DAT3__SD1_DATA3		| MUX_PAD_CTRL(USDHC_PAD_CTRL)),
	IOMUX_PADS(PAD_CSI0_DAT18__GPIO6_IO04	| NO_PAD_CTRL_SION_CFG), /* CD */
	IOMUX_PADS(PAD_DI0_PIN4__GPIO4_IO20		| NO_PAD_CTRL_SION_CFG), /* WP */
};

/* Modulo WiFi SDIO
 *
 * SD2
 *
 * */
static iomux_v3_cfg_t const mx6_usdhc2_pads[] = {
	IOMUX_PADS(PAD_SD2_CLK__SD2_CLK			| MUX_PAD_CTRL(USDHC_PAD_CTRL)),
	IOMUX_PADS(PAD_SD2_CMD__SD2_CMD			| MUX_PAD_CTRL(USDHC_PAD_CTRL)),
	IOMUX_PADS(PAD_SD2_DAT0__SD2_DATA0		| MUX_PAD_CTRL(USDHC_PAD_CTRL)),
	IOMUX_PADS(PAD_SD2_DAT1__SD2_DATA1		| MUX_PAD_CTRL(USDHC_PAD_CTRL)),
	IOMUX_PADS(PAD_SD2_DAT2__SD2_DATA2		| MUX_PAD_CTRL(USDHC_PAD_CTRL)),
	IOMUX_PADS(PAD_SD2_DAT3__SD2_DATA3		| MUX_PAD_CTRL(USDHC_PAD_CTRL)),
};

static void my_sd_init_mux(void)
{
	SETUP_IOMUX_PADS(mx6_usdhc1_pads);
}

static void my_sdio_wifi_init_mux(void)
{
	SETUP_IOMUX_PADS(mx6_usdhc2_pads);
}

/*
 * USB OTG
 *
 * */

static iomux_v3_cfg_t const usbotg_pads[] = {
	IOMUX_PADS(PAD_ENET_RX_ER__USB_OTG_ID	| DIO_PAD_CFG),
	IOMUX_PADS(PAD_GPIO_5__GPIO1_IO05 		| DIO_PAD_CFG), /* OVER CURRENT UNUSED */
	IOMUX_PADS(PAD_GPIO_6__GPIO1_IO06 		| DIO_PAD_CFG), /* OTG PWR EN */
};

/*
 * HOST USB 1
 *
 * */
static iomux_v3_cfg_t const usbh1_pads[] = {
	IOMUX_PADS(PAD_EIM_D30__GPIO3_IO30 		| DIO_PAD_CFG), /* OVER CURRENT UNUSED */
	IOMUX_PADS(PAD_ENET_TXD0__GPIO1_IO30 	| DIO_PAD_CFG), /* USB H1 PWR EN */

};

static void my_usb_init_mux(void)
{
	SETUP_IOMUX_PADS(usbotg_pads);
	/*set daisy chain for otg_pin_id on 6q. for 6dl, this bit is reserved*/
	imx_iomux_set_gpr_register(1, 13, 1, 0);

	SETUP_IOMUX_PADS(usbh1_pads);
}

/**
 * eeprom modulo e carrier
 */
static iomux_v3_cfg_t const eeprom_pads[] = {
	IOMUX_PADS(PAD_ENET_RXD0__GPIO1_IO27	| DIO_PAD_CFG), // eeprom_wp modulo
	IOMUX_PADS(PAD_KEY_COL2__GPIO4_IO10		| DIO_PAD_CFG), // EEP_WP carrier
};

static void my_eeprom_init_mux(void)
{
	SETUP_IOMUX_PADS(eeprom_pads);
}

static iomux_v3_cfg_t const gpio_pads[] = {
	// BT+BLE
	IOMUX_PADS(PAD_CSI0_VSYNC__GPIO5_IO21 	| DIO_PAD_PDOWN_CFG), // WMD_PWR_EN_3V3 - GPIO 149
	IOMUX_PADS(PAD_EIM_A16__GPIO2_IO22		| DIO_PAD_PDOWN_CFG), // WLAN_EN_3V3 - GPIO 54
	IOMUX_PADS(PAD_EIM_A17__GPIO2_IO21		| DIO_PAD_PDOWN_CFG), // BT_EN_3V3 - GPIO 53
	IOMUX_PADS(PAD_CSI0_DAT12__GPIO5_IO30	| DIO_PAD_CFG), // WLAN_IRQ_3V3 - GPIO 158

	IOMUX_PADS(PAD_GPIO_18__GPIO7_IO13		| DIO_PAD_CFG), // PMIC_nINT
	IOMUX_PADS(PAD_SD4_DAT1__PWM3_OUT		| DIO_PAD_CFG), // Buzzer

	//allarme temperatura
	IOMUX_PADS(PAD_CSI0_DAT13__GPIO5_IO31	| DIO_PAD_CFG), // TEMP_ALERT_3V3 - GPIO 159

	//gpio expander
	IOMUX_PADS(PAD_GPIO_19__GPIO4_IO05	| DIO_PAD_CFG), // EXP_nIRQ - GPIO 101
	IOMUX_PADS(PAD_EIM_A19__GPIO2_IO19	| DIO_PUP_PAD_CFG), // EXP_nRST - GPIO 51

	//leds
	IOMUX_PADS(PAD_EIM_A20__GPIO2_IO18	| DIO_PAD_PDOWN_CFG), // EXP_LED1 - GPIO 50
	IOMUX_PADS(PAD_EIM_A21__GPIO2_IO17	| DIO_PAD_PDOWN_CFG), // EXP_LED2 - GPIO 49

	//rtc
	IOMUX_PADS(PAD_CSI0_DAT16__GPIO6_IO02	| DIO_PAD_CFG), // RTC_MFP - GPIO 162

	//extio
	IOMUX_PADS(PAD_CSI0_DAT17__GPIO6_IO03	| DIO_PAD_CFG), // EXTIO_IN1 - GPIO 163
	IOMUX_PADS(PAD_CSI0_MCLK__GPIO5_IO19	| DIO_PAD_CFG), // EXTIO_OUT1 - GPIO 147

	//various
	IOMUX_PADS(PAD_GPIO_4__GPIO1_IO04		| NO_PAD_CTRL_SION_CFG), // Wifi CD (PGF0533_A01) or GPIO (PGF0533_A02) */
	IOMUX_PADS(PAD_GPIO_2__GPIO1_IO02		| NO_PAD_CTRL_SION_CFG), // Wifi WP (PGF0533_A01) or RTC_CLKOE (PGF0533_A02)*/
	IOMUX_PADS(PAD_GPIO_17__GPIO7_IO12		| DIO_PAD_CFG),	 // TS_n4w-5w (PGF0533_A01) or TS-BUSY (PGF0533_A02)
};

static void my_gpio_init_mux(void)
{
	SETUP_IOMUX_PADS(gpio_pads);
	// Release sx1509 reset
	gpio_direction_output(IMX_GPIO_NR(2, 19),1);
}

static iomux_v3_cfg_t const can_pads[] = {
	IOMUX_PADS(PAD_KEY_ROW4__FLEXCAN2_RX	| NO_PAD_CTRL_SION_CFG),
	IOMUX_PADS(PAD_KEY_COL4__FLEXCAN2_TX	| NO_PAD_CTRL_SION_CFG),
};

static void my_can_init_mux(void)
{
	SETUP_IOMUX_PADS(can_pads);
}

static iomux_v3_cfg_t const cam_digital_pads[] = {
	IOMUX_PADS(PAD_SD4_DAT3__GPIO2_IO11 	| DIO_PAD_CFG), // CAMD_nRST_3V3
	IOMUX_PADS(PAD_SD4_DAT0__GPIO2_IO08 	| DIO_PAD_CFG), // CAMD_PWDN_3V3
	IOMUX_PADS(PAD_GPIO_0__CCM_CLKO1		| MUX_PAD_CTRL(NO_PAD_CTRL)), // CAMD_CSI0_MCK_3V3
};

static void my_cam_init_mux(void)
{
	SETUP_IOMUX_PADS(cam_digital_pads);
}

static iomux_v3_cfg_t const audio_pads[] = {
	IOMUX_PADS(PAD_CSI0_DAT6__AUD3_TXFS | MUX_PAD_CTRL(AUDIO_PAD_CTRL)), // AUDIO_I2S_LRCLK
	IOMUX_PADS(PAD_CSI0_DAT4__AUD3_TXC 	| MUX_PAD_CTRL(AUDIO_PAD_CTRL)),  // AUDIO_I2S_SCLK
	IOMUX_PADS(PAD_CSI0_DAT7__AUD3_RXD 	| MUX_PAD_CTRL(AUDIO_PAD_CTRL)), // AUDIO_I2S_DIN
	IOMUX_PADS(PAD_CSI0_DAT5__AUD3_TXD 	| MUX_PAD_CTRL(AUDIO_PAD_CTRL)), // AUDIO_I2S_DOUT
	IOMUX_PADS(PAD_NANDF_CS2__CCM_CLKO2 | MUX_PAD_CTRL(AUDIO_PAD_CTRL)), // AUDIO_MCLK
};

static void my_audio_init_mux(void)
{
	SETUP_IOMUX_PADS(audio_pads);
}

static iomux_v3_cfg_t const display0_pads[] = {
	IOMUX_PADS(PAD_EIM_DA8__GPIO3_IO08 		| DIO_PAD_CFG),  	// BKL0_PWR_EN - GPIO 72
	IOMUX_PADS(PAD_NANDF_CS3__GPIO6_IO16 	| DIO_PAD_CFG),  	// DISP0_EN - GPIO 176
	IOMUX_PADS(PAD_SD4_DAT2__GPIO2_IO10		| DIO_PAD_CFG),		// BKL0_PWM
	IOMUX_PADS(PAD_CSI0_DATA_EN__GPIO5_IO20	| DIO_PAD_CFG),		// LVDS0_GPIO
	IOMUX_PADS(PAD_DI0_DISP_CLK__IPU1_DI0_DISP_CLK | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DI0_PIN15__IPU1_DI0_PIN15 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DI0_PIN2__IPU1_DI0_PIN02 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DI0_PIN3__IPU1_DI0_PIN03 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT0__IPU1_DISP0_DATA00 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT1__IPU1_DISP0_DATA01 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT2__IPU1_DISP0_DATA02 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT3__IPU1_DISP0_DATA03 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT4__IPU1_DISP0_DATA04 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT5__IPU1_DISP0_DATA05 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT6__IPU1_DISP0_DATA06 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT7__IPU1_DISP0_DATA07 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT8__IPU1_DISP0_DATA08 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT9__IPU1_DISP0_DATA09 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT10__IPU1_DISP0_DATA10 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT11__IPU1_DISP0_DATA11 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT12__IPU1_DISP0_DATA12 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT13__IPU1_DISP0_DATA13 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT14__IPU1_DISP0_DATA14 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT15__IPU1_DISP0_DATA15 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT16__IPU1_DISP0_DATA16 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT17__IPU1_DISP0_DATA17 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT18__IPU1_DISP0_DATA18 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT19__IPU1_DISP0_DATA19 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT20__IPU1_DISP0_DATA20 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT21__IPU1_DISP0_DATA21 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT22__IPU1_DISP0_DATA22 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
	IOMUX_PADS(PAD_DISP0_DAT23__IPU1_DISP0_DATA23 | MUX_PAD_CTRL(DISP_PAD_CTRL)),
};

static void my_display0_init_mux(void)
{
	SETUP_IOMUX_PADS(display0_pads);
}

static iomux_v3_cfg_t const display1_pads[] = {
	IOMUX_PADS(PAD_EIM_LBA__GPIO2_IO27 	| DIO_PAD_CFG),  	// DISP1_EN - GPIO 59
	IOMUX_PADS(PAD_CSI0_PIXCLK__GPIO5_IO18 	| DIO_PAD_CFG),		// LVDS1_GPIO - GPIO 146
	IOMUX_PADS(PAD_GPIO_9__GPIO1_IO09	| DIO_PAD_CFG),		// BKL1_PWM
	IOMUX_PADS(PAD_EIM_DA14__GPIO3_IO14 | DIO_PAD_CFG), 	// BKL1_PWR_EN - GPIO 78
};

static void my_display1_init_mux(void)
{
	SETUP_IOMUX_PADS(display1_pads);
}

static iomux_v3_cfg_t const power_management_pads[] = {
	IOMUX_PADS(PAD_GPIO_3__GPIO1_IO03			| DIO_PAD_CFG), // PWR_5V0_EN_3V3
	IOMUX_PADS(PAD_NANDF_CS1__GPIO6_IO14		| DIO_PAD_CFG), // VIO_3V3_EN
};

static void my_power_management_init_mux(void)
{
	SETUP_IOMUX_PADS(power_management_pads);
}

static iomux_v3_cfg_t const hdmi_pads[] = {
	IOMUX_PADS(PAD_KEY_ROW2__HDMI_TX_CEC_LINE	| HDMI_CEC_PAD_CTRL), // HDMI_CEC
};

/* Pinmux changes to correctly terminate pin on depopulated boards */
void egf_wid0533ab0101_mux(void)
{
	gpio_direction_output(IMX_GPIO_NR(3,27),0); //TS-nATT_3V3

	SETUP_IOMUX_PAD(PAD_CSI0_DAT6__GPIO5_IO24 | DIO_PAD_PDOWN_CFG);
	gpio_direction_output(IMX_GPIO_NR(5,24),0); // AUDIO_I2S_LRCLK
	SETUP_IOMUX_PAD(PAD_CSI0_DAT4__GPIO5_IO22 	| DIO_PAD_PDOWN_CFG);
	gpio_direction_output(IMX_GPIO_NR(5,22),0); // AUDIO_I2S_SCLK
	SETUP_IOMUX_PAD(PAD_CSI0_DAT7__GPIO5_IO25	| DIO_PAD_PDOWN_CFG);
	gpio_direction_output(IMX_GPIO_NR(5,25),0); // AUDIO_I2S_DIN
	SETUP_IOMUX_PAD(PAD_CSI0_DAT5__GPIO5_IO23	| DIO_PAD_PDOWN_CFG);
	gpio_direction_output(IMX_GPIO_NR(5,23),0); // AUDIO_I2S_DOUT
	SETUP_IOMUX_PAD(PAD_NANDF_CS2__GPIO6_IO15 | DIO_PUP_PAD_CFG); // AUDIO_MCLK
	gpio_direction_output(IMX_GPIO_NR(6,15),1);

	/* UART 1 */
	SETUP_IOMUX_PAD(PAD_CSI0_DAT10__GPIO5_IO28 | DIO_PUP_PAD_CFG);
	gpio_direction_output(IMX_GPIO_NR(5,28),1);
	SETUP_IOMUX_PAD(PAD_CSI0_DAT11__GPIO5_IO29 | DIO_PAD_PDOWN_CFG);
	gpio_direction_output(IMX_GPIO_NR(5,29),0);
	SETUP_IOMUX_PAD(PAD_EIM_D19__GPIO3_IO19 | DIO_PUP_PAD_CFG);
	gpio_direction_output(IMX_GPIO_NR(3,19),1);
	SETUP_IOMUX_PAD(PAD_EIM_D20__GPIO3_IO20 | DIO_PAD_PDOWN_CFG);
	gpio_direction_output(IMX_GPIO_NR(3,20),0);

	/* UART 2 */
	SETUP_IOMUX_PAD(PAD_SD4_DAT7__GPIO2_IO15 | DIO_PUP_PAD_CFG);
	gpio_direction_output(IMX_GPIO_NR(2,15),1);
	SETUP_IOMUX_PAD(PAD_SD4_DAT4__GPIO2_IO12 | DIO_PAD_PDOWN_CFG);
	gpio_direction_output(IMX_GPIO_NR(2,12),0);
	SETUP_IOMUX_PAD(PAD_SD4_DAT6__GPIO2_IO14 | DIO_PUP_PAD_CFG);
	gpio_direction_output(IMX_GPIO_NR(2,14),1);
	SETUP_IOMUX_PAD(PAD_SD4_DAT5__GPIO2_IO13 | DIO_PAD_PDOWN_CFG);
	gpio_direction_output(IMX_GPIO_NR(2,13),0);

	SETUP_IOMUX_PAD(PAD_KEY_ROW4__GPIO4_IO15	| DIO_PAD_PDOWN_CFG);
	gpio_direction_output(IMX_GPIO_NR(4,15),0);
	SETUP_IOMUX_PAD(PAD_KEY_COL4__GPIO4_IO14	| DIO_PAD_PDOWN_CFG);
	gpio_direction_output(IMX_GPIO_NR(4,14),0);

	gpio_direction_output(IMX_GPIO_NR(6,3),0); // EXTIO_IN1 - GPIO 163
}

/* Pinmux changes to correctly terminate pin on depopulated boards */
void egf_wid0533bc0101_mux(void)
{
	gpio_direction_output(IMX_GPIO_NR(3,27),0); //TS-nATT_3V3

	SETUP_IOMUX_PAD(PAD_CSI0_DAT6__GPIO5_IO24 | DIO_PAD_PDOWN_CFG);
	gpio_direction_output(IMX_GPIO_NR(5,24),0); // AUDIO_I2S_LRCLK
	SETUP_IOMUX_PAD(PAD_CSI0_DAT4__GPIO5_IO22 	| DIO_PAD_PDOWN_CFG);
	gpio_direction_output(IMX_GPIO_NR(5,22),0); // AUDIO_I2S_SCLK
	SETUP_IOMUX_PAD(PAD_CSI0_DAT7__GPIO5_IO25	| DIO_PAD_PDOWN_CFG);
	gpio_direction_output(IMX_GPIO_NR(5,25),0); // AUDIO_I2S_DIN
	SETUP_IOMUX_PAD(PAD_CSI0_DAT5__GPIO5_IO23	| DIO_PAD_PDOWN_CFG);
	gpio_direction_output(IMX_GPIO_NR(5,23),0); // AUDIO_I2S_DOUT
	SETUP_IOMUX_PAD(PAD_NANDF_CS2__GPIO6_IO15 | DIO_PUP_PAD_CFG); // AUDIO_MCLK
	gpio_direction_output(IMX_GPIO_NR(6,15),1);

	/* UART 1 */
	SETUP_IOMUX_PAD(PAD_EIM_D19__GPIO3_IO19 | DIO_PUP_PAD_CFG);
	gpio_direction_output(IMX_GPIO_NR(3,19),1);
	SETUP_IOMUX_PAD(PAD_EIM_D20__GPIO3_IO20 | DIO_PAD_PDOWN_CFG);
	gpio_direction_output(IMX_GPIO_NR(3,20),0);

	/* UART 2 */
	SETUP_IOMUX_PAD(PAD_SD4_DAT7__GPIO2_IO15 | DIO_PUP_PAD_CFG);
	gpio_direction_output(IMX_GPIO_NR(2,15),1);
	SETUP_IOMUX_PAD(PAD_SD4_DAT4__GPIO2_IO12 | DIO_PAD_PDOWN_CFG);
	gpio_direction_output(IMX_GPIO_NR(2,12),0);
	SETUP_IOMUX_PAD(PAD_SD4_DAT6__GPIO2_IO14 | DIO_PUP_PAD_CFG);
	gpio_direction_output(IMX_GPIO_NR(2,14),1);
	SETUP_IOMUX_PAD(PAD_SD4_DAT5__GPIO2_IO13 | DIO_PAD_PDOWN_CFG);
	gpio_direction_output(IMX_GPIO_NR(2,13),0);

	SETUP_IOMUX_PAD(PAD_KEY_ROW4__GPIO4_IO15	| DIO_PAD_PDOWN_CFG);
	gpio_direction_output(IMX_GPIO_NR(4,15),0);
	SETUP_IOMUX_PAD(PAD_KEY_COL4__GPIO4_IO14	| DIO_PAD_PDOWN_CFG);
	gpio_direction_output(IMX_GPIO_NR(4,14),0);

	gpio_direction_output(IMX_GPIO_NR(6,3),0); // EXTIO_IN1 - GPIO 163
}


void pgf_0533_a02_mux(void)
{
	SETUP_IOMUX_PAD(PAD_EIM_A23__GPIO6_IO06 | DIO_PAD_PDOWN_CFG); //LCD-PWR-EN
	SETUP_IOMUX_PAD(PAD_EIM_A22__GPIO2_IO16 | DIO_PAD_PDOWN_CFG); //UART2-SHDN
	SETUP_IOMUX_PAD(PAD_EIM_DA0__GPIO3_IO00 | DIO_PAD_PDOWN_CFG); //UART2-RS485-DUPLEX-SEL
	SETUP_IOMUX_PAD(PAD_EIM_DA1__GPIO3_IO01 | DIO_PAD_PDOWN_CFG); //UART2-RS232-RS485-MODE
	SETUP_IOMUX_PAD(PAD_EIM_DA2__GPIO3_IO02 | DIO_PAD_PDOWN_CFG); //UART2-RS485-ECHO
	SETUP_IOMUX_PAD(PAD_EIM_DA3__GPIO3_IO03 | DIO_PUP_PAD_CFG);   //UART2-SLEW

	my_wd_init_mux();

	// Configure UART2 as active, RS232, high baudrate
	gpio_direction_output(IMX_GPIO_NR(2,16), 1); // UART2-SHDN = 1
	gpio_direction_output(IMX_GPIO_NR(3, 1), 0); // UART2-RS232-RS485-MODE = 0
	gpio_direction_output(IMX_GPIO_NR(3, 3), 1); // UART2-SLEW = 1

	gpio_direction_output(IMX_GPIO_NR(1, 4), 1); // RTC-CLKOE = 1

}

void egf_board_common_mux_init(int mode)
{
	switch(mode){
	case PROGRAMMER_MUX_MODE:
		my_power_management_init_mux();
		my_uart_init_mux();
		my_gpio_init_mux();
		my_i2c_init_mux();
		my_enet_init_mux();
		my_spi4_init_mux();
		my_sd_init_mux();
		my_emmc_init_mux();
		my_spinor_init_mux();
		my_display0_init_mux();
		my_display1_init_mux();
		my_usb_init_mux();
		break;
	case APPLICATION_MUX_MODE:
		my_power_management_init_mux();
		my_uart_init_mux();
		my_gpio_init_mux();
		my_i2c_init_mux();
		my_spi4_init_mux();
		my_spinor_init_mux();
		my_touch_init_mux();
		my_enet_init_mux();
		my_emmc_init_mux();
		my_sd_init_mux();
		my_sdio_wifi_init_mux();
		my_usb_init_mux();
		my_eeprom_init_mux();
		my_cam_init_mux();
		my_audio_init_mux();
		my_can_init_mux();
		my_spi2_init_mux();
		my_display0_init_mux();
		my_display1_init_mux();
		break;
	default:
		printf("MUX MODE NOT DEFINED!!!!!!!!!!!!\n");
		break;
	}
}


